server:
  port: 9999

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.201:8848
        metadata:
          weight: 2
          socketPort : ${game.gateway.server.config.port}
  rabbitmq:
    host: 106.52.151.187
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
  redis:
    database: 0
    host: 106.52.151.187
    port: 6379
    timeout: 3000
    enable: true
    jedis.pool:
      max-active: 50
      max-wait: 3000
      max-idle: 50
      min-idle: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: warn
game:
  gateway:
    config:
      port: 6666  # 游戏网关的长连接端口，这里的数据是自定义配置。
      boss-thread-count: 1
      work-thread-count: 4
#  topic:
#    config:
#      server-id: 1001
#      business-game-message-topic: business-game-message-topic # 向游戏服务发送消息 的Topic前缀
#      gateway-game-message-topic: gateway-game-message-topic #接收游戏服务响应消息的Topic
#      topic-group-id: ${game.server.config.server-id}