server:
  port: 8082

spring:
  application:
    name: Server-Provider
  shardingsphere:
    datasource:
      names: cloud0,cloud1,cloud2
    sharding:
      # 默认分表策略
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: cloud$->{id%2}
      # 默认分布式id生成器
      default-key-generator:
        type: SEQ
        column: id
      # 主从节点配置
      master-slave-rules:
        cloud0:
          # maser数据源
          master-data-source-name: cloud0
          # slave数据源
          slave-data-source-names: cloud2
        cloud1:
          # maser数据源
          master-data-source-name: cloud1
          # slave数据源
          slave-data-source-names: cloud2
      tables:
        # hc_question_reply_record 分库分表配置
        hc_question_reply_record:
          # 真实数据节点  hc_question_reply_record_2020_q1
          actual-data-nodes: cloud$->{0..1}.hc_question_reply_record_$->{2020..2025}_q$->{0..1}
          # 表分片策略
          table-strategy:
            standard:
              # 分片键
              sharding-column: reply_wheel_time
              # 精确分片算法
              preciseAlgorithmClassName: com.hzoom.demo.sharding.DatePreciseShardingAlgorithm
              # 范围分片算法，用于BETWEEN，可选。。该类需实现RangeShardingAlgorithm接口并提供无参数的构造器
              rangeAlgorithmClassName: com.hzoom.demo.sharding.DateRangeShardingAlgorithm
          default-database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: cloud$->{[0,1]} #数据节点,均匀分布


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
        cloud0:
          url: jdbc:mysql://106.52.151.187:3306/cloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: 123
        cloud1:
          url: jdbc:mysql://106.52.151.187:3306/cloud1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: 123
      slave:
        cloud2:
          url: jdbc:mysql://106.52.151.187:3306/cloud2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: 123
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /monitor/druid/*
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 0
    host: 106.52.151.187
    port: 6379
    timeout: 3000
    enable: true
    jedis.pool:
      max-active: 50
      max-wait: 3000
      max-idle: 50
      min-idle: 10

  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://106.52.151.187:9411/ # 指定了 Zipkin 服务器的地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8083/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1 #eureka和应用A在同一个局域网内，那么eureka默认暴露的是应用A在内网的地址。你需要在A应用注册eureka时配置使用外网IP
    instance-id: ${eureka.instance.ip-address}:${server.port}:${random.value}
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8888/xxl-job-admin
    executor:
      appname: 'xxl-job-executor-spring'
      logretentiondays: 30
      logpath: /data/applogs/xxl-job/jobhandler
    enabled: false
#      ip: 192.168.1.30
#      port: 9999
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,beans
core:
  filter:
    enable: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

netty-websocket:
  host: 0.0.0.0

  path: /ws/*
  port: 8889

  path2: /test
  port2: 9999

  path3: /wstest
es:
  enable: false