server:
  port: 8888
zk:
  enable: true
  connectionString: "106.52.151.187:2181"
spring:
  application:
    name: im-web
  rabbitmq:
    host: 106.52.151.187
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.201:8848
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8888/
          predicates:
            - Path=/foo/**
          filters:
            - RewritePath=/foo/(?<segment>.*),/user/$\{segment}
        - id: route2
          uri:  http://localhost:8888/
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - RequestTime=false
      default-filters:
    stream:
      bindings:
        input1:
          #指定输入通道对应的主题名
          destination: minestream
          #指定该应用实例属于 stream 消费组
          group: group
#          consumer:
#            #通过该参数开启消费者分区功能
#            partitioned: true
        output1:
          destination: minestream
#          producer:
#            #通过该参数指定了分区键的表达式规则，可以根据实际的输出消息规则配置 SpEL 来生成合适的分区键
#            partitionKeyExpression: payload
#            partitionCount: 2
#      #该参数指定了当前消费者的总实例数量
#      instance-count: 2
#      #该参数设置了当前实例的索引号，从 0 开始，最大值为 spring.cloud.stream.instance-count 参数 - 1
#      instance-index: 0

management:
  health:
    elasticsearch:
      enabled: false
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'