server:
  port: 8082

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8083/eureka/
    registerWithEureka: false # false表示不向注册中心注册自己
    fetchRegistry: false   # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
  server:
    enable-self-preservation: false
