server:
  port: 9000
  
spring:
  application:
    name: Server-Consumer
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8080/eureka/

feign:
  hystrix:
    enabled: true
logging:
  level:
    com:
      example:
        demo:
          service:
            UserService: debug
