server:
  port: 1234

spring:
  application:
    name: Eureka_Consumer
  security:
    user:
      name: root
      password: 123

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8080/eureka/

feign:
  hystrix:
    enabled: false

logging:
  level:
    com:
      example:
        demo:
          service:
            UserService: debug
