server:
  port: 1234

spring:
  application:
    name: Eureka_Consumer
  security:
    user:
      name: root
      password: 123

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8080/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 106.52.151.187 #eureka和应用A在同一个局域网内，那么eureka默认暴露的是应用A在内网的地址。你需要在A应用注册eureka时配置使用外网IP
    instance-id: ${eureka.instance.ip-address}:${server.port}
    
feign:
  hystrix:
    enabled: false

logging:
  level:
    com:
      example:
        demo:
          service:
            UserService: debug
