spring:
  application:
    name: Zuul_Gateway
server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8080/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      url: http://localhost:8082
    api-b:
      path: /api-b/**
      serviceId: server-provider
    api-c:
      path: /api-c/**
      serviceId: server-consumer
    api-d:
      path: /api-c/user/1
      serviceId: lol
    api-e:
      path: /api-e/**
      url: forward:/test
  ignored-services: server-consumer
  sensitive-headers:
  add-host-header: true