spring:
  application:
    name: Zuul_Gateway
  security:
    user:
      name: root
      password: 123
  sleuth:
    web:
      client:
        enabled: true
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8080/eureka/
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: Server-Provider
    consumer:
      path: /consumer/**
      serviceId: Eureka_Consumer
    test:
      path: /test/**
      url: forward:/test
#  ignored-services: Eureka_Consumer
  sensitive-headers:
  add-host-header: true