spring:
  application:
    name: Zuul_Gateway
  security:
    user:
      name: root
      password: 123
server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8080/eureka/
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: server-provider
    consumer:
      path: /consumer/**
      serviceId: server-consumer
    test:
      path: /test/**
      url: forward:/test
  ignored-services: server-consumer
  sensitive-headers:
  add-host-header: true