server:
  port: 5003


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.201:8848
  data:
    mongodb:
      host: 106.52.151.187
      port: 27017
      database: hzoom
  redis:
    database: 0
    host: 106.52.151.187
    port: 6379
    timeout: 3000
    enable: true
    jedis.pool:
      max-active: 50
      max-wait: 3000
      max-idle: 50
      min-idle: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

datasource:
  master: cloud0
  enable: true
  map:
    cloud0:
      url: jdbc:mysql://106.52.151.187:3306/cloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 123
      type: write
    cloud1:
      url: jdbc:mysql://106.52.151.187:3306/cloud1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 123
      type: write
    cloud2:
      url: jdbc:mysql://106.52.151.187:3306/cloud2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 123
      type: read