server:
  port: 5003


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.201:8848
  data:
    mongodb:
      host: 106.52.151.187
      port: 27017
      database: hzoom
  redis:
    database: 0
    host: 106.52.151.187
    port: 6379
    timeout: 3000
    enable: true
    jedis.pool:
      max-active: 50
      max-wait: 3000
      max-idle: 50
      min-idle: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'