server:
  port: 9998
spring:
  application:
    name: Zuul_Service
  security:
    user:
      name: root
      password: 123
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://106.52.151.187:9411/ # 指定了 Zipkin 服务器的地址

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8083/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1 #eureka和应用A在同一个局域网内，那么eureka默认暴露的是应用A在内网的地址。你需要在A应用注册eureka时配置使用外网IP
    instance-id: ${eureka.instance.ip-address}:${server.port}:${random.value}
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: Server-Provider
    consumer:
      path: /consumer/**
      serviceId: Eureka_Consumer
    test:
      path: /test/**
      url: forward:/test
#  ignored-services: Eureka_Consumer
  sensitive-headers:
  add-host-header: true