server:
  port: 12580

spring:
  application:
    name: Config_Server
  security:
    user:
      name: root
      password: 123
  cloud:
    config:
      server:
        git:
          uri: ENC(X/srgivpKoVLuwHHLJ537GjK1YTMPmVqHQ4+X/ue3ruU2fl61HWc1ZLcuenJQpDx)
          username: ENC(44a/TH12S5VeFVfVjt9SYQ==)
          password: ENC(fXSfMb9nOk0rS9jwXZ1VP32rlnQu7aFx)
          search-paths:
            - '/*'
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: 106.52.151.187
    port: 5672
    username: guest
    password: guest
#使用bus需要配置的
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8083/eureka/

#jasypt加密的密匙
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7


